version: '3.8'
services:
  postgres:
    image: postgres:15 
    container_name: blog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 666password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    ports:
      - "4001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:666password@postgres:5432/blog_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
