services:
  postgres:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 666password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:  # 把資料庫檔案持久化（儲存在主機上），不會隨容器刪除而消失
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # 當 Docker 重啟時，自動重啟此容器，除非手動停止

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    ports:
      - "4001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:666password@postgres:5432/blog_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
