services:
  postgres:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 666password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432" # 主機 port : 容器 port
    volumes:  # 把資料庫檔案持久化（儲存在主機上），不會隨容器刪除而消失
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # 當 Docker 重啟時，自動重啟此容器，除非手動停止

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    ports:
      - "4001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:666password@postgres:5432/blog_db
    depends_on:
      - postgres # 確保啟動順序，啟動 backend 前要先啟動 postgres
    volumes:
      - ./backend:/app # 把專案資料夾掛載到 docker 上的 /app 位置
      - backend_node_modules:/app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # args:
      #   NEXT_PUBLIC_API_URL: http://localhost:4001/api
    container_name: blog_frontend
    ports:
      - "4000:3000"
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:4001/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
